<?xml version="1.0" ?>
<robot name="ur5_2fgripper" xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:include filename="$(find robot_model_config)/urdf/ur5_model.urdf.xacro" />	
	<xacro:include filename="$(find robot_model_config)/urdf/kinect_sensor_macro.xacro"/>
	<xacro:include filename="$(find robot_model_config)/urdf/simple_2fgripper_macro.xacro"/>

	<!-- property list -->
	<xacro:property name="workcell_height" value="1"/>
	<xacro:property name="workcell_length" value="2.775"/>
	<xacro:property name="workcell_width" value="2.220"/>	
	<xacro:property name="workcell_thickness" value="0.04"/>
	<xacro:property name="robot_stand_height" value="0.20"/>
	<xacro:property name="worktable_thickness" value="0.02"/>
	<xacro:property name="worktable_leg_radius" value="0.02"/>
	<xacro:property name="arm_prefix" value=""/>
	<material name="blue">
		<color rgba="0 0 1 1"/>
	</material>
	<material name="yellow">
		<color rgba="0 1 1 1"/>
	</material>
	<material name="gray_transparent">
		<color rgba="0.6 0.6 0.6 0.4"/>
	</material>
	<material name="blue_transparent">
		<color rgba="0 0.8 1 0.4"/>
	</material>

	<!-- instantiating arm and gripper -->	
	<xacro:ur5_robot prefix="${arm_prefix}"/>
	<xacro:simple_2fgripper_link prefix="${arm_prefix}"/>
	
	<!-- utility macros -->
		<xacro:macro name="table_leg_component" params="x y z l r">
			<visual>
				<origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
				<geometry>
					<cylinder radius="${r}" length="${h}"/>
				</geometry>
				<material name="blue"/>
			</visual>
			<collision>
				<origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
				<geometry>
					<cylinder radius="${r}" length="${h}"/>
				</geometry>
				<material name="yellow"/>
			</collision>		
		</xacro:macro>

		<xacro:macro name="work_table_link" params="name l w h">
			<link name="${name}">
				<visual>
					<origin xyz="0 0 ${-0.5*worktable_thickness}" rpy="0 0 0"/>
					<geometry>
						<box size="${l} ${w} ${worktable_thickness}"/>
					</geometry>
					<material name="blue"/>
				</visual>
				<collision>
					<origin xyz="0 0 ${-0.5*worktable_thickness}" rpy="0 0 0"/>
					<geometry>
						<box size="${l} ${w} ${worktable_thickness}"/>
					</geometry>
					<material name="yellow"/>
				</collision>	
				<xacro:table_leg_component x="${0.5*l - 2*worktable_leg_radius}" y="${0.5*w - 2*worktable_leg_radius}" 
					z="${-0.5*h-worktable_thickness}" l="${h - worktable_thickness}" r="${worktable_leg_radius}"/>
				<xacro:table_leg_component x="-${0.5*l - 2*worktable_leg_radius}" y="${0.5*w - 2*worktable_leg_radius}" 
					z="${-0.5*h-worktable_thickness}" l="${h - worktable_thickness}" r="${worktable_leg_radius}"/>
				<xacro:table_leg_component x="${0.5*l - 2*worktable_leg_radius}" y="-${0.5*w - 2*worktable_leg_radius}" 
					z="${-0.5*h-worktable_thickness}" l="${h - worktable_thickness}" r="${worktable_leg_radius}"/>
				<xacro:table_leg_component x="-${0.5*l - 2*worktable_leg_radius}" y="-${0.5*w - 2*worktable_leg_radius}" 
					z="${-0.5*h-worktable_thickness}" l="${h - worktable_thickness}" r="${worktable_leg_radius}"/>
			</link>
		</xacro:macro>


		<!-- geometry macros -->	
		<xacro:macro name="workcell_geometry" params="length width height *color_block">
				<geometry>
					<box size="${length} ${width} ${height}"/>
				</geometry>			
				<xacro:insert_block name="color_block"/>
		</xacro:macro>	
		<xacro:macro name="workcell_element" params="name parent length width height offset_x offset_y">
			<link name="${name}">
				<visual>
					<xacro:workcell_geometry length="${length}" width="${width}" height="${height}">
						<material name="gray_transparent"/>
					</xacro:workcell_geometry>
				</visual>
				<collision>
					<xacro:workcell_geometry length="${length}" width="${width}" height="${height}">
						<material name="blue_transparent"/>
					</xacro:workcell_geometry>
				</collision>
			</link>
			<joint name="${parent}_to_${name}" type="fixed">
				<parent link="${parent}"/>
				<child link="${name}"/>
				<origin xyz="${offset_x} ${offset_y} ${0.5 * height}" rpy="0 0 0"/>
			</joint>		
		</xacro:macro>
		<!-- end of geometry macros -->


	<!-- workcell bounds macro -->
		<xacro:macro name="workcell_bounds">

			<link name="roof2">
				<collision>
					<origin xyz="0 0 ${workcell_height }" rpy="0 0 0"/>
					<xacro:workcell_geometry length="${workcell_length * 0.5}"
						 width="${workcell_width}" height="${workcell_thickness}">
						<material name="blue_transparent"/>
					</xacro:workcell_geometry>
				</collision>
			</link>

			<joint name="workcell_to_roof2" type="fixed">
				<parent link="world_frame"/>
				<child link="roof2"/>
				<origin xyz="${workcell_length * -0.25} 0 0" rpy="0 0 0"/>
			</joint>
			<xacro:workcell_element name="front_wall2" parent="world_frame"
				 length="0.1" width="2.220" height="${workcell_height}" offset_x="-1.3375" offset_y="0"/>		 
			<xacro:workcell_element name="back_wall2" parent="world_frame"
				 length="0.04" width="2.00" height="${workcell_height}" offset_x="0.20" offset_y="0"/>
			<xacro:workcell_element name="left_wall2" parent="world_frame" 
				length="1.384" width="0.1" height="${workcell_height}" offset_x="-0.601" offset_y="1.060"/>
			<xacro:workcell_element name="right_wall2" parent="world_frame" 
				length="1.384" width="0.1" height="${workcell_height}" offset_x="-0.601" offset_y="-1.060"/>
		</xacro:macro>
	<!-- end of workcell bounds macro -->

	<!-- workcell components -->
		<link name="world_frame"/>
		<xacro:workcell_bounds/>

		<!--<xacro:work_table_link name="${arm_prefix}worktable" l="1.0" w="1.0" h="0.5"/>-->

		<link name="${arm_prefix}alignment_surface">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<box size="1.2 1.2 0.01"/>
				</geometry>
				<material name="blue"/>
			</visual>
		</link>

		<link name="ur5_stand">
			<visual>
				<geometry>
					<cylinder radius="0.0735" length="${robot_stand_height}"/>
				</geometry>
				<material name="orange_transparent"/>
			</visual>
			<collision>
				<geometry>
					<cylinder radius="0.0735" length="${robot_stand_height}"/>
				</geometry>
				<material name="blue_transparent"/>
			</collision>
		</link>


	<!-- collision avoidance support components -->
		<link name="base_padding">
			<collision>
				<geometry>
					<cylinder radius="0.14" length="${robot_stand_height * 2}"/>
				</geometry>
				<material name="blue_transparent"/>
			</collision>
		</link>

	<!-- sensor components -->
		<xacro:sensor_definitions prefix="${arm_prefix}" parent_link="ur5_stand" 
			x_val="0.0" y_val="-0.810" z_val="0.6" roll="0.037" pitch="0.494" yaw="2.321" /> 


	<!-- joints -->
		<joint name="world_to_stand" type="fixed">
			<parent link="world_frame"/>
			<child link="ur5_stand"/>
			<origin xyz="-0.238 0 ${robot_stand_height * 0.5}"/>
		</joint>


		<joint name="world_to_base_padding" type="fixed">
			<parent link="world_frame"/>
			<child link="base_padding"/>
			<origin xyz="-0.238 0 ${robot_stand_height}"/>
		</joint>

		<joint name="stand_to_base" type="fixed">
			<parent link="ur5_stand"/>
			<child link="${arm_prefix}base_link"/>
			<origin xyz="0 0 ${robot_stand_height * 0.5}" rpy="0 0 -3.1415"/>
		</joint>

		<joint name="world_to_alignment_surface" type="fixed">
			<parent link="world_frame"/>
			<child link="${arm_prefix}alignment_surface"/>
			<origin xyz="-1.20 0 0" rpy="0 0 0"/>
		</joint>

		<!--<joint name="world_to_table" type="fixed">
			<parent link="world_frame"/>
			<child link="${arm_prefix}worktable"/>
			<origin xyz="-1.02 0 0" rpy="0 0 0"/>
		</joint>-->
		
		<joint name="${arm_prefix}to_gripper" type="fixed">
			<parent link="${arm_prefix}ee_link"/>
			<child link="${arm_prefix}gripper_frame"/>
			<origin xyz="0 0 0" rpy="0 1.57 0"/> <!-- 0 1.57 0 -->
		</joint>
</robot>
