<?xml version="1.0" ?>
<robot name="ur5_2fgripper" xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:include filename="$(find robot_model_config)/urdf/ur5_model.urdf.xacro" />	
	<xacro:include filename="$(find robot_model_config)/urdf/kinect_sensor_macro.xacro"/>
	<xacro:include filename="$(find robot_model_config)/urdf/simple_2fgripper_macro.xacro"/>

	<!-- property list -->
	<xacro:property name="workcell_height" value="1"/>
	<xacro:property name="robot_stand_height" value="0.20"/>
	<xacro:property name="worktable_thickness" value="0.02"/>
	<xacro:property name="worktable_leg_radius" value="0.02"/>
	<xacro:property name="arm_prefix" value=""/>
	<material name="blue">
		<color rgba="0 0 1 1"/>
	</material>
	<material name="yellow">
		<color rgba="0 1 1 1"/>
	</material>

	<!-- instantiating arm and gripper -->	
	<xacro:ur5_robot prefix="${arm_prefix}"/>
	<xacro:simple_2fgripper_link prefix="${arm_prefix}"/>
	
	<!-- utility macros -->
		<xacro:macro name="table_leg_component" params="x y z l r">
			<visual>
				<origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
				<geometry>
					<cylinder radius="${r}" length="${h}"/>
				</geometry>
				<material name="blue"/>
			</visual>
			<collision>
				<origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
				<geometry>
					<cylinder radius="${r}" length="${h}"/>
				</geometry>
				<material name="yellow"/>
			</collision>		
		</xacro:macro>

		<xacro:macro name="work_table_link" params="name l w h">
			<link name="${name}">
				<visual>
					<origin xyz="0 0 ${-0.5*worktable_thickness}" rpy="0 0 0"/>
					<geometry>
						<box size="${l} ${w} ${worktable_thickness}"/>
					</geometry>
					<material name="blue"/>
				</visual>
				<collision>
					<origin xyz="0 0 ${-0.5*worktable_thickness}" rpy="0 0 0"/>
					<geometry>
						<box size="${l} ${w} ${worktable_thickness}"/>
					</geometry>
					<material name="yellow"/>
				</collision>	
				<xacro:table_leg_component x="${0.5*l - 2*worktable_leg_radius}" y="${0.5*w - 2*worktable_leg_radius}" 
					z="${-0.5*h-worktable_thickness}" l="${h - worktable_thickness}" r="${worktable_leg_radius}"/>
				<xacro:table_leg_component x="-${0.5*l - 2*worktable_leg_radius}" y="${0.5*w - 2*worktable_leg_radius}" 
					z="${-0.5*h-worktable_thickness}" l="${h - worktable_thickness}" r="${worktable_leg_radius}"/>
				<xacro:table_leg_component x="${0.5*l - 2*worktable_leg_radius}" y="-${0.5*w - 2*worktable_leg_radius}" 
					z="${-0.5*h-worktable_thickness}" l="${h - worktable_thickness}" r="${worktable_leg_radius}"/>
				<xacro:table_leg_component x="-${0.5*l - 2*worktable_leg_radius}" y="-${0.5*w - 2*worktable_leg_radius}" 
					z="${-0.5*h-worktable_thickness}" l="${h - worktable_thickness}" r="${worktable_leg_radius}"/>
			</link>
		</xacro:macro>


	<!-- workcell components -->

		<link name="world_frame"/>

		<xacro:work_table_link name="${arm_prefix}worktable" l="1.0" w="1.0" h="0.5"/>

		<link name="ur5_stand">
			<visual>
				<geometry>
					<cylinder radius="0.0735" length="${robot_stand_height}"/>
				</geometry>
				<material name="orange_transparent"/>
			</visual>
			<collision>
				<geometry>
					<cylinder radius="0.0735" length="${robot_stand_height}"/>
				</geometry>
				<material name="blue_transparent"/>
			</collision>
		</link>


	<!-- collision avoidance support components -->
		<link name="base_padding">
			<collision>
				<geometry>
					<cylinder radius="0.14" length="${robot_stand_height * 2}"/>
				</geometry>
				<material name="blue_transparent"/>
			</collision>
		</link>

	<!-- sensor components -->
		<xacro:sensor_definitions prefix="${arm_prefix}" parent_link="ur5_stand" 
			x_val="-1.20" y_val="0.190" z_val="1.015" pitch="1.145" yaw="0.035" roll="0.019" /> 


	<!-- joints -->
		<joint name="world_to_stand" type="fixed">
			<parent link="world_frame"/>
			<child link="ur5_stand"/>
			<origin xyz="-0.238 0 ${robot_stand_height * 0.5}"/>
		</joint>


		<joint name="world_to_base_padding" type="fixed">
			<parent link="world_frame"/>
			<child link="base_padding"/>
			<origin xyz="-0.238 0 ${robot_stand_height}"/>
		</joint>

		<joint name="stand_to_base" type="fixed">
			<parent link="ur5_stand"/>
			<child link="${arm_prefix}base_link"/>
			<origin xyz="0 0 ${robot_stand_height * 0.5}" rpy="0 0 3.1416"/>
		</joint>

		<joint name="world_to_table" type="fixed">
			<parent link="world_frame"/>
			<child link="${arm_prefix}worktable"/>
			<origin xyz="-1.02 0 0" rpy="0 0 0"/>
		</joint>
		
		<joint name="${arm_prefix}to_gripper" type="fixed">
			<parent link="${arm_prefix}ee_link"/>
			<child link="${arm_prefix}gripper_frame"/>
			<origin xyz="0 0 0" rpy="0 1.57 0"/> <!-- 0 1.57 0 -->
		</joint>
</robot>
