world_frame_id: world_frame
arm_group_name: manipulator
tcp_link_name: tcp_frame
attached_object_link: attached_object_link
wrist_link_name: tcp_frame
home_pose_name: home
wait_pose_name: wait
approach_distance: 0.1
retreat_distance: 0.1
gripper_workrange: 0.087
touch_links: [wrist_1_link, wrist_2_link, wrist_3_link, tcp_frame, gripper_body]
tcp_to_target_pose:
  x: 0.0
  y: 0.0
  z: 0.0
  rx: -1.57
  ry: 0.0
  rz: 0.0
world_to_place_pose:
  x: -0.6
  y: 0.6
  z: 0.17
  rx: 1.57
  ry: 0.0
  rz: 0.0
